In [9]:
!pip install numpy



[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [10]:
import numpy as np

In [11]:
print(np.__version__)

2.4.3


In [ ]:
## Creating Arrays

In [12]:
list1 = [1,2,3]
print(list1)

[1, 2, 3]


In [15]:
arr_list1 = np.array(list1)
print(arr_list1)

[1 2 3]


In [14]:
print(type(arr_list1))

<class 'numpy.ndarray'>


In [20]:
print(arr_list1.ndim)

1


In [16]:
list1 = [1,2,3]
list2 = [4,5,6]
arr_list1_2 = np.array([list1  ,list2])
print(arr_list1_2)

[[1 2 3]
 [4 5 6]]


In [22]:
print(arr_list1_2.ndim)

2


In [18]:
list1 = [1,2,3]
list2 = [4,5,6]
list3 = [7,8,9]
arr_list1_3 = np.array([[list1  ,list2,list3]])
print(arr_list1_3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [19]:
print(arr_list1_3.ndim)

3


In [ ]:
## numpy array attribute

In [23]:
arr1 = np.array([[1,2,3] , [4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [27]:
print("Shape" , arr1.shape)
print("Size" , arr1.size)
print("dType" , arr1.dtype)
print("n_dim" ,arr1.ndim)

Shape (2, 3)
Size 6
dType int64
n_dim 2


In [ ]:
## Array Initialization method

In [30]:
#zeros Array
zero_arr = np.zeros((2,3))
print(zero_arr )

[[0. 0. 0.]
 [0. 0. 0.]]


In [32]:
## one array
one_arr = np.ones((1,3))
print(one_arr)

[[1. 1. 1.]]


In [36]:
## full array
full_arr = np.full((3,2),8)
print(full_arr)

[[8 8]
 [8 8]
 [8 8]]
